### ISSUE TITLE
Remove deprecated warning messages from mini_exiftool

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/assembly-objectfile#1]
Which is coming from mini_exiftool:

https://github.com/janfri/mini_exiftool/blob/master/lib/mini_exiftool.rb#L94

   Option :convert_encoding is not longer supported!
    Please use the String#encod\* methods.

**Comment by ndushay** [comment]
this is 7 years old and i can't find it in honeybadger.  closing.
