### ISSUE TITLE
refactor: ObjectFileable should just be part of ObjectFile

### ISSUE THREAD

**Issue by atz** [sul-dlss/assembly-objectfile#10]
A module should not be concerned with `initialize` and `instance_vars`.  `ObjectFileable` has all the concerns of a class: move its logic into `ObjectFile`.

sadly `ObjectFileable`  is used in the assembly-image gem

**Comment by ndushay** [comment]
sadly ObjectFileable is used in the assembly-image gem.  Closing this.

**Comment by ndushay** [comment]
assigning to @jcoyne because he has 2 competing open PRs related to this.  It's not a priority -- just noting.
