### ISSUE TITLE
determine why some files formerly identified as "application/octet-stream" are being identified as image file types

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/assembly-objectfile#103]
In looking into some recent issues with disk image accessioning, we found that something has changed in the mimetype identification logic for preassembly and assemblyWF.

Some files previously identified as "application/octet-stream" earlier this year are now being identified as unusual file types, such as image/x-tga or image/g3fax. 

Example:

[jj996kk5869](https://argo.stanford.edu/view/jj996kk5869) was accessioned in February and the file "jj996kk5869-1.img" was identified back then as "application/octet-stream". 

I accessioned that file in QA yesterday and it's now being identified as "image/x-tga". It's definitely not a Targa image and the generic "application/octet-stream" is a more appropriate mimetype for it. Something seems to have changed in how we determine the mimetype but I'm not sure what.

**Comment by jcoyne** [comment]
See my earlier investigation here:
https://github.com/sul-dlss/assembly-objectfile/issues/98#issuecomment-1232100382

**Comment by andrewjbtw** [comment]
Closing this as the answer is indeed `file` has changed:

On a CentOS system, the results for the same file are:
```
[pres@preservation-catalog-prod-05 experiment]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.9 (Maipo)
Release:	7.9
Codename:	Maipo
[pres@preservation-catalog-prod-05 experiment]$ file jj996kk5869-1.img 
jj996kk5869-1.img: D64 Image
[pres@preservation-catalog-prod-05 experiment]$ file --mime-type jj996kk5869-1.img 
jj996kk5869-1.img: application/octet-stream
```
