### ISSUE TITLE
ObjectFileable#exif swallows errors

### ISSUE THREAD

**Issue by atz** [sul-dlss/assembly-objectfile#11]
`README` says having exiftool installed is a pre-requisite.  But then `ObjectFileable`'s `exif` method swallows the errors that occur from not having it installed.  This seems like a mismatch of expectations.  Other operational or data errors might warrant swallowing, but not having a pre-requisite installed should be a clear `raise`, since literally nothing can succeed without it.

**Comment by ndushay** [comment]
swallowing errors isn't good.  Perhaps we can send a HoneyBadger.notify instead?

**Comment by jcoyne** [comment]
@ndushay assembly-objectfile doesn't depend on Honeybadger, but raising an error in a project that is connected to Honeybadger would result in a Honeybadger notification.

**Comment by ndushay** [comment]
The actions to be taken for this ticket:

- have the gem raise an exception
- have all consumers of the gem catch the gem's exception and do something like a HoneyBadger.notify and then continue, as it does now (it continues)

**Comment by jcoyne** [comment]
@ndushay I thought the point of this ticket was that it should not continue if it is misconfigured.  I'm trying to square that with

> then continue, as it does now (it continues)

**Comment by ndushay** [comment]
@jcoyne I would say we have a win to at first determine what the HB errors we've been missing ARE;  then we can assess if we should stop processing.   It is also reasonable to just assume we should stop processing.  Either is okay.

**Comment by ndushay** [comment]
gem with changes has been released.  It should be updated on Monday, Jun 6 with dep updates.
