### ISSUE TITLE
Support for 3D data

### ISSUE THREAD

**Issue by snydman** [sul-dlss/assembly-objectfile#15]
per @blalbrit and https://jirasul.stanford.edu/jira/browse/DEVQUEUE-229

- Update https://github.com/sul-dlss/assembly-objectfile/blob/317a421855e14b8a219eb931640a16325561d6ad/lib/assembly-objectfile.rb (and any other location) to manage defaults for obj, ply, threejs, GLTF, etc. type files
- Possibly same codebase... unknown... set mimetype for obj, ply, threejs GLTF, etc. type files that currently fail to provide mimetypes

**Comment by peetucket** [comment]
Duplicate of #6
