### ISSUE TITLE
Optional parameter to specify book reading direction when creating contentMetadata 

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/assembly-objectfile#16]
When creating metadata for content type of "book", the caller of the `.create_content_metadata` should be able to specify the reading direction.  If not supplied or set to 'ltr', no action is needed.  If set to 'rtl', then need to add a new node just below the top level '<contentMetadata>' declaration: 

```<bookData readingOrder="rtl" pageStart="right"/>```

See https://consul.stanford.edu/display/chimera/DOR+content+types,+resource+types+and+interpretive+metadata for full documentation

**Comment by jcoyne** [comment]
Why don't we always add this node on book types?  Wouldn't that be more consistent?

**Comment by peetucket** [comment]
Yes, it would be more consistent if the book direction node was added to all contentMetadata of type=book (even ltr) and we could easily do this.  May want to discuss if we'd rather have consistency with reading direction always specified vs consistency with the >300k objects already accessioned (99.9% of which do not specify the default ltr direction).

**Comment by ndushay** [comment]
@peetucket is this now moot?  Or just ... done?

**Comment by peetucket** [comment]
Probably moot.
