### ISSUE TITLE
Assign mimetypes manually if current methods do not work

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/assembly-objectfile#19]
This roll-up Jira ticket (https://jirasul.stanford.edu/jira/browse/DEVQUEUE-229) suggests that some 3d file extensions may not have their mimetypes set correctly.

Currently (as of Aug 15 2019) mimetypes are determined by the gem via:

1. Looking at any exif data in the file
2. Using the mime-type gem https://github.com/mime-types/ruby-mime-types

If both of these fail to produce a mimetype, you get a blank value.

Note: #20 adds the unix file system in second priority above the mimetype gem, which seems to produce the expected mimetype of .obj files.  This may fix the problem.

If this is not acceptable, we could add a new mechanism, which uses some configuration file to manually map extensions to mimetypes.

**Comment by ndushay** [comment]
@peetucket do you have any idea if this is still a problem?

**Comment by peetucket** [comment]
I do not know, but I don't think we changed how mime-types are determined, so it may still be a problem (though I have not been tracking if there are any more reports of issues).

**Comment by andrewjbtw** [comment]
Mime-type identification remains a problem, with downstream effects on access systems - broken text search, lack of streaming display, maybe some other issues I haven't seen yet. 

It's not clear how to work the ability to set them manually into the accessioning process itself. They are editable via the structural metadata CSV.

**Comment by andrewjbtw** [comment]
There are preservation systems (like Archivematica) where you can choose which method of file type identification you would like to apply on a per-ingest basis. The SDR UI doesn't have a place for that kind of user-driven choice at this point. 

Users are more likely to know when they want extension matching and when they want a tool that determines format based on file analysis than we are likely to pick one method and automate it successfully for everyone.

**Comment by ndushay** [comment]
See issue #72 for switching to `lipvips` for mimetypes;  maybe that will help.

**Comment by mjgiarlo** [comment]
In the SDR world, we currently have **at least** three different spots where we capture MIME types for files, and they all use different strategies:

1. `assembly-objectfile`
  a. Hard-coded override based on file extension (to get proper JSON and VTT types)
  b. Use `exif` for certain types (based on `file` tool)
  c. Run *nix `file` tool
  d. Determine based on file extension
2. `sdr-api`
  a. If file comes from Globus, use `marcel` gem to determine the MIME type given a path to a file---`marcel` will use a combination of file content and the file name/extension to make its determination.
  b. If file lives in sdr-api as a deposited blob, use whatever ActiveStorage has determined is the MIME type (IIRC, it uses `marcel` per the Globus strategy above) **unless** the type is `application/x-stanford-json`, in which case we set the MIME type to `application/json`, and if nothing has been set, default to `application/octet-stream`.
3. `technical-metadata-service`
  a. Use `siegfried`, with some logic to correct how WARC files are identified

At the same time, we don't have a shared understanding of how/where `assembly-objectfile` fits into the picture, so we are considering a story-time in the upcoming Media work cycle to delve into the subject before prescribing a solution to the shortcoming identified in this issue.

**Comment by mjgiarlo** [comment]
@andrewjbtw Given the analysis above, I'm inclined to close this issue in favor of something more targeted, once we have a better sense of the problem(s) we're trying to solve, e.g., what's being misidentified where. Thoughts?

**Comment by andrewjbtw** [comment]
I think that's fine. It looks like this ticket came out of work on 3D content that has not been revisited in a few years. We're also better able to support setting mimetypes via Argo than we once were, which is a path to remediating content if an inaccurate or imprecise mimetype was generated during accessioning.
