### ISSUE TITLE
Images used for texture and normal map with 3D objects are not shelved.

### ISSUE THREAD

**Issue by calavano** [sul-dlss/assembly-objectfile#30]
Objects accessioned using the pre-assembly tool using the "3D" content structure do not properly render in the purl. The problem is that the texture and normal map files get accessioned with shelve=false.

The mime-types of the texture files are typically image/jpeg, but could also be image/png.

An example druid that used preassembly and exhibits the problem is: cm433fr7636

**Comment by peetucket** [comment]
Holding the PR for now - there may be another way to do this by asking accessioneers to set publish/preserve/shelve for all file types for 3d objects instead of making a special case for jpeg files.

**Comment by peetucket** [comment]
@calavano and @andrewjbtw : thoughts on if just using the ability in pre-assembly to force publish/preserve/shelve by project is a solution for 3D objects for now, or if we should move forward with shelving any jpegs/pngs by default across all projects?

**Comment by andrewjbtw** [comment]
We discussed this yesterday afternoon in the SDR admin meeting and came to the conclusion that in the short run, using the pre-assembly option to set everything to yes is sufficient.

In the longer run, an approach with a manifest, similar to the media manifest, is preferable to changing defaults at the mimetype level. I will ticket that separately with the understanding that it might not be part of the current workcycle.

**Comment by peetucket** [comment]
Ok, i close this ticket and the associated PR
