### ISSUE TITLE
Produce correct contentMetadata for 3d content type

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/assembly-objectfile#6]
pending PR noted below 

- [x] depends on sul-dlss/assembly#65 -->  ported to common-accessioning here https://github.com/sul-dlss/common-accessioning/pull/366

- [x] Allow for a new style called "3d" which produces the correct contentMetadata (to be speced). 
see https://consul.stanford.edu/display/chimera/DOR+content+types%2C+resource+types+and+interpretive+metadata

- [x] fix mimetypes issues: sul-dlss/assembly-objectfile#20

**Comment by ndushay** [comment]
@peetucket if this isn't < 1 day to finish up (the whole of it), put it on the SDR backlog -- there are higher priorities.
