### ISSUE TITLE
exif-collect is failing on a druid that contains a disk image + video + images + other content

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/assembly-objectfile#98]
**Describe the bug**
The exif-collect step of the assemblyWF is hitting an error when trying to calculate the height of at least one of the files in https://argo.stanford.edu/view/druid:vk510zh2040  

There is an HB error but it doesn't show the file name and this item has 1117 files: https://app.honeybadger.io/projects/52894/faults/86541414

The "imageheight" property should only be calculated for still image formats, but the only still image formats in this druid are JP2 and NEF files and when I accession those in stage there are no errors.

My suspicion is that the problem has to do with the disk image files. These have filenames like:

```
vk510zh2040_SC1031_CM001.001
vk510zh2040_SC1031_CM001.002
vk510zh2040_SC1031_CM001.003
vk510zh2040_SC1031_CM001.004
vk510zh2040_SC1031_CM001.005
vk510zh2040_SC1031_CM001.006
vk510zh2040_SC1031_CM001.007
vk510zh2040_SC1031_CM001.008
vk510zh2040_SC1031_CM001.009
vk510zh2040_SC1031_CM001.010
```

These are segments of a full disk image and it's possible that one of the assemblyWF tools is misidentifying one of the segments as a still image, attempting to calculate the height, and then failing. 

The disk has over 300 parts, totaling over 450 GB, which makes it too large to test on stage.

**User Impact**
This is blocking accessioning of this druid.

**Additional context**
If we can figure out which file(s) are problematic, we can work out what to do about them. We might need a new strategy for handling disk image parts, such as a way to override the mimetype identification so that no height or width are calculated.

**Comment by jcoyne** [comment]
@andrewjbtw this is really odd, because it shouldn't be in that area of the code unless it identified the file as an image: https://github.com/sul-dlss/common-accessioning/blob/43c7924310fa0ebf4ca4415ef2659d8de83040ed/lib/robots/dor_repo/assembly/exif_collect.rb#L35

**Comment by jcoyne** [comment]
Here's how we can find the bad file:
```ruby
druid = "druid:vk510zh2040"
=> "druid:vk510zh2040"
assembly_item = Dor::Assembly::Item.new druid: druid
 cocina_model = assembly_item.cocina_model
 
 file_sets = cocina_model.structural.to_h.fetch(:contains)
file_sets.each do |file_set|
    files = file_set.dig(:structural, :contains)
    files.each do |file|
      object_file = ::Assembly::ObjectFile.new(assembly_item.path_finder.path_to_content_file(file.fetch(:filename)))
      puts file.fetch(:filename) if object_file.image? && !object_file.exif
    end
 end
```
